In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### `np.arange `
: Creates an array from {starting_num} to {finishing_num -1} with steps

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.zeros / np.ones : create an array with 0s or 1s

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `np.linspace(0,5,10)`
: 10 evenly spaced points from 0 to 5

In [13]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### `np.eye(4) `
: identity matrix with the size of 4

In [1]:
np.eye(4)

NameError: name 'np' is not defined

### `np.random.rand(5)`
: one-dimensional array with 5 random numbers

In [15]:
np.random.rand(5)

array([0.93712702, 0.27664784, 0.52299373, 0.37943786, 0.15839628])

In [17]:
np.random.rand(5,5)

array([[0.41758764, 0.31161991, 0.75505305, 0.49549277, 0.50362048],
       [0.70890954, 0.77929367, 0.36194086, 0.13638956, 0.17288262],
       [0.33534427, 0.83277219, 0.83379751, 0.24239346, 0.07271327],
       [0.37544785, 0.4236257 , 0.29956358, 0.25242133, 0.96405453],
       [0.41337027, 0.4016788 , 0.55230917, 0.6749197 , 0.69782815]])

### `np.random.randn`
random numbers following normal distribution

In [22]:
np.random.randn(10,10)

array([[ 1.85553911,  0.07341787, -0.55251827,  0.58562257, -0.1150218 ,
         0.76294652, -0.28843113,  0.66811678, -1.41984995, -0.03238635],
       [-0.38131275,  1.22225108,  1.51052783,  0.3547421 , -0.17522328,
        -1.046864  ,  0.78214702, -0.53837389,  1.23948792, -0.12653109],
       [-0.90219585,  0.88154369, -0.49837098, -0.55933024,  0.82837002,
        -0.05838254,  0.36838753,  0.93787413,  0.77752465,  0.74271382],
       [-1.169083  ,  0.18779096, -1.77654231, -1.43920918,  0.21369033,
        -1.3080926 ,  0.69250777, -0.99020099,  1.66739876,  0.70279688],
       [ 0.19424941,  0.44528003,  1.34976881, -0.31047333,  0.01935772,
         1.02073717, -0.41024751,  0.39618753,  0.43309413,  1.23159956],
       [-1.7699273 , -1.15464145, -0.09040524,  0.38368143,  1.13855912,
        -0.20541549, -1.29721084,  1.05471977,  0.12851734, -1.12033428],
       [ 1.09778735,  0.88753382, -0.25959758,  0.33341892,  1.35957689,
         1.32827314, -1.98992601, -1.24012031

### `np.random.randint(1,100, 10) `
:  choose 10 random integer between one and 99

In [23]:
np.random.randint(1,100,10)

array([67,  4, 59, 30, 75, 13, 73, 15, 69, 45])

### Test Exercise

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([ 6,  3, 10, 48, 46, 14, 32, 26, 48, 35])

In [34]:
ranarr.max()

48

### `argmax`
:location of max value

In [36]:
ranarr.argmax()

3

### `argmin`
: location of min value

In [37]:
ranarr.argmin()

1

In [35]:
ranarr.min()

3

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### `shape`
: show the dimensions of an array

In [41]:
ranarr.shape

(10,)

### `dtype`
: show the data type of an array

In [42]:
ranarr.dtype

dtype('int32')

In [45]:
from numpy.random import randint

In [47]:
randint(2,10,10)

array([8, 5, 9, 3, 9, 8, 6, 7, 6, 2])