# Numpy Indexing and selction

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:]= 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

## !shallow copy is done through slicing!
- this is done to reduce the memory usage

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Deep Copy 

In [18]:
test_arr = np.arange(0,11)

In [19]:
test_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
deep_array = test_arr.copy()

In [21]:
deep_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
deep_array[:] = 100

In [23]:
deep_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
test_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*** In this case, the original array has not changed ***

In [25]:
shallow_array = test_arr[0:4]

In [26]:
shallow_array[:]=100

In [27]:
test_arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

*** In this case, the original array has changed ***

# 2d Arrays

In [28]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

*** Access the first element in the first row ***  
`arr_2d[0][0] == arr_2d[0,0]`

In [44]:
arr_2d[0][0]

5

**Access the first row**

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

## Conditions with arrays

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_arr = arr>5

In [36]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [40]:
arr[arr<3]

array([1, 2])

In [42]:
arr_2d = np.arange(50).reshape(5,10)

In [43]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

grab 13, 14

In [44]:
arr_2d[1,3:5]

array([13, 14])

grab 25,26

In [46]:
arr_2d[2,5:7]

array([25, 26])